// File generated by FlutterFire CLI (firebase_options.dart).
// Run: flutterfire configure
// IMPORTANT: Replace placeholder values with your actual Firebase config.
// See README.md for setup instructions.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('FamilyOS does not support web platform.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not configured for this platform: $defaultTargetPlatform',
        );
    }
  }

  // ─── REPLACE WITH YOUR FIREBASE CONFIG ────────────────────────────────────
  // Run: flutterfire configure --project=<your-firebase-project>
  // Or copy from: Firebase Console → Project Settings → Your Apps
  // ──────────────────────────────────────────────────────────────────────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:000000000000:android:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-familyos-project',
    storageBucket: 'your-familyos-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'your-familyos-project',
    storageBucket: 'your-familyos-project.appspot.com',
    iosBundleId: 'com.yourcompany.familyos',
  );
}
